"""novo schema

Revision ID: cfb978675e29
Revises: ed54d08f920c
Create Date: 2025-09-13 18:36:14.079446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb978675e29'
down_revision = 'ed54d08f920c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
