"""empty message

Revision ID: ed54d08f920c
Revises: bc5027e7800f
Create Date: 2025-09-13 13:57:51.480052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed54d08f920c'
down_revision = 'bc5027e7800f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
